---
# This playbook  deploys the quarkus

- name: Clone the charts repo
  ansible.builtin.git:
    repo: https://github.com/ibm-garage-ref-storefront/inventory-ms-quarkus
    dest: /tmp
    clone: yes

- name: helm dependency update
  command: helm dependency update /tmp/inventory-ms-quarkus/chart/base -n quarkus

- name: helm dependency update
  command: helm install quarkus /tmp/inventory-ms-quarkus/chart/base --namespace quarkus --debug

- name: expose route
  command: oc expose svc quarkus-base -n quarkus

- name: get route
  command: oc get route quarkus-base --template='{{.spec.host}}'
