---
# This playbook  deploys the quarkus

- name: helm dependency update
  command: helm dependency update /tmp/inventory-ms-quarkus/chart/base -n quarkus

- name: helm dependency update
  command: helm install quarkus /tmp/inventory-ms-quarkus/chart/base --namespace quarkus --debug

- name: expose route
  command: oc expose svc quarkus-base -n quarkus

- name: get route
  command: oc get route quarkus-base --template='{{.spec.host}}'